name: Mission Log
description: Leave a message on my GitHub profile.
title: "[Mission Log]"
labels:
  - guestbook

body:
  - type: input
    id: name
    attributes:
      label: Callsign
      placeholder: Your GitHub Username

  - type: textarea
    id: message
    attributes:
      label: Mission Log
      placeholder: Leave a message...

    validations:
      required: true
